### ISSUE TITLE
Option \G does not works

### ISSUE THREAD

**Issue by porzioj** [formulahendry/vscode-mysql#13]
I would like to use the \G option to show result vertically.

**Comment by formulahendry** [comment]
Do you meet with any error message? What's the output?

**Comment by porzioj** [comment]
Maybe I don't use the right synthax...
`SELECT * FORM table; `
works perfectly
But the view is the standard mysql output command so i would like to use the \G option:
`SELECT * FROM table \G `
return a parse error : 
**ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\G' at line 1**

Is there a way to have a different output ?

Thanks

**Comment by formulahendry** [comment]
I think `\G` would only work on MySQL CLI. MySQL Workbench also does not support `\G`.
![image](https://user-images.githubusercontent.com/1050213/34508077-f5311438-f076-11e7-9f23-fff7718dce21.png)
So closing this issue, and use #14 to track the feature request to display query results vertically
