### ISSUE TITLE
Error: ER_NOT_SUPPORTED_ AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by z0z0r4** [formulahendry/vscode-mysql#193]
Mysql 8.0 login with root
Any fix this?
https://github.com/formulahendry/vscode-mysql/issues/99

**Comment by burguitoscat** [comment]
Type in MySQL console:
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
when 'root' is your user, 'localhost' is your server name and 'password' is your password

**Comment by FrankyYanFuzhang** [comment]
> Type in MySQL console: ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'; when 'root' is your user, 'localhost' is your server name and 'password' is your password

Work on my machine, thanks a lot!

**Comment by emheyarssi** [comment]
> Type in MySQL console:
> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
> when 'root' is your user, 'localhost' is your server name and 'password' is your password

This is very discouraged on production servers.

**Comment by aliyuthman** [comment]
While MYSQL Server supported Standard (mysql_native_password), caching_sha2_password, and SHA256. It is more secure to use a more recommended authentication type (caching_sha2_password or SHA256) than using the Standard (using SHA-1 hashing algorithm) which is not recommended.
