### ISSUE TITLE
The extension only dhows the first 100 tables of the database

### ISSUE THREAD

**Issue by benedekAdam** [formulahendry/vscode-mysql#2]
I often work with databases containing more than a 100 tables (164 currently), and I can't see them in the table list as it cuts off after 100.

**Comment by formulahendry** [comment]
Hi @benedekAdam , I have increased the default max table count to 500. And you could also update this value `vscode-mysql.maxTableCount`: https://github.com/formulahendry/vscode-mysql#settings

**Comment by benedekAdam** [comment]
Thank you very much!
