### ISSUE TITLE
Can be hidden but cannot be restored

### ISSUE THREAD

**Issue by kklou** [formulahendry/vscode-mysql#24]
i used ubuntu 1604 linux kernel 4.4.0.-116.
the MySQL bar can be hidden, but no way to restored it.

**Comment by formulahendry** [comment]
Right click on the `EXPLORER`
![image](https://user-images.githubusercontent.com/1050213/36640404-c8557b14-1a58-11e8-940f-e8d1f54799eb.png)

**Comment by kklou** [comment]
thanks a lot. Got it.
