### ISSUE TITLE
MySQL Parser

### ISSUE THREAD

**Issue by underscores** [formulahendry/vscode-mysql#4]
When Parsing longer SQL scripts it will fail. The error message will point to any statement after a certain amount of characters. For example in one of my scripts for creating multiple tables in a larger schema it cut off in line 7 the word "AUTO_INCREMENT" to "AUTO_INCRE" and spawned a syntax error. 
What I have tried:
 - written a longer SQL script
 - ending each statement with a semicolon 
What I have not tried:
 - encapsulating each statement in Begin and End
Possible Issue: 
 The SQL parser does not work properly and seems to be limited in amount of signs it can actually    process at once.

**Comment by formulahendry** [comment]
Hi @underscores , could you please share some screenshots of the longer SQL you have tried and the error message?

**Comment by underscores** [comment]
I will send you more information by tomorrow when I have access to the project again.

**Comment by underscores** [comment]
Code example: 
https://pastebin.com/F1qxVKMG
Error Message:
"Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS Test2 ( 
  IDtest2 INT NOT NULL PRIMARY KEY AUTO_INCRE' at line 7"

If I add "BEGIN" and "END" it will cut away exactly the length of "BEGIN" from AUTO_INCREMENT.

**Comment by formulahendry** [comment]
Hi @underscores , the root cause is that this extension does not support multiple statement queries. Now, I have added support for multiple statement queries. Please install the new version and have a try. Let me know if it works as you expected.
