### ISSUE TITLE
Is there support for MySQL installations on WSL (Ubuntu 16.04)?

### ISSUE THREAD

**Issue by zachsa** [formulahendry/vscode-mysql#45]
Is there a way to connect to a MySQL installation on Windows Subsystem for Linux (Ubuntu 16.04)? I had to specify that MySQL use the TCP protocol - not sure if this is relevant or not...

**Comment by formulahendry** [comment]
How do you connect to the MySQL on WSL with other tool?

**Comment by zachsa** [comment]
Ah - apologies. I just realized the mysql server wasn't running. Because it's hosted in WSL I need to 1) start an instance of Ubuntu and 2) make start mysql.

Doing that, I CAN actually connect to a MySQL instance.

Thank you for the reply
