### ISSUE TITLE
display 顯示

### ISSUE THREAD

**Issue by swdcgghxa** [formulahendry/vscode-mysql#56]
希望有更多表格樣式.
I hope there are more table styles.

**Comment by formulahendry** [comment]
Could you share more info? What style do you want?

**Comment by Charlie-lies** [comment]
查询结果显示的表格是用HTML语句来写的。
在 .vscode\extensions\formulahendry.vscode-mysql-0.4.0\out里面，找到sqlResultWebView.js，用vscode打开就可以修改。
`class SqlResultWebView {
    static show(data, title) {
        const panel = vscode.window.createWebviewPanel("MySQL", title, vscode.ViewColumn.Two, {
            retainContextWhenHidden: true,
        });
        panel.webview.html = SqlResultWebView.getWebviewContent(data);
    }
    static getWebviewContent(data) {
        const head = [].concat("<!DOCTYPE html>", "<html>", "<head>", '<meta http-equiv="Content-type" content="text/html;charset=UTF-8">', "<style>table{border-collapse:collapse; }table,td,th{border:1px dotted #ccc; padding:5px;}th {background:#444} </style>", "</head>", "<body>").join("\n");
        const body = SqlResultWebView.render(data);
        const tail = [
            "</body>",
            "</html>",
        ].join("\n");
        return head + body + tail;
    }`
