### ISSUE TITLE
FR: support SSL connection

### ISSUE THREAD

**Issue by jbpoulsen** [formulahendry/vscode-mysql#6]
Hey there, glad to see someone finally making a dedicated MySQL extension for VSCode.

Im using an Azure MySQL server with an SSL connection and im getting an SSL error because the connection is not secured with a certificate.
![image](https://user-images.githubusercontent.com/13856797/33446618-e62645d4-d600-11e7-8562-66082f6288bb.png)

Is there any way we can support this? Maybe a file-path as an optional parameter when adding a new MySQL instance to VSCode?

**Comment by formulahendry** [comment]
Hi @jbpoulsen , currently it is not supported yet. For quick turnaround, you could disable the **Enforce SSL connection** in Azure portal.

![image](https://user-images.githubusercontent.com/1050213/33488622-3762080c-d6ec-11e7-8665-c913367c5562.png)

**Comment by formulahendry** [comment]
Thanks @jbpoulsen 's PR #7

**Comment by vaimeo** [comment]
now is it available ?

**Comment by NicoRun** [comment]
Hi all!

I'm trying to use this extension in my Visual Studio code but not working.

Here the error message : _Connection error! UNKNOWN_CODE_PLEASE_REPORT: SSL connection is required. Please specify SSL options and retry_

The MySQL database is in an Azure subscription. 

First try was when SSL OFF, same error. Second try with SSL ON, still not working.

My connection is successful with MySQLWorkBench.

Any advice ?

Thank you in advance!
