### ISSUE TITLE
How to connect with Private Key ??

### ISSUE THREAD

**Issue by aroraayush** [formulahendry/vscode-mysql#62]
My MySQL DB is on a remote server that I can connect by SSH. I have the usename & password of the DB and the PEM key to connect to the remote Server. How to connect with such configuration ??

**Comment by formulahendry** [comment]
Please see the usage section: https://github.com/formulahendry/vscode-mysql#usage Did you meet with any issue?

**Comment by fulldecent** [comment]
Is this a duplicate of #1?

**Comment by schuster-rainer** [comment]
@aroraayush use a ssh tunnel like described in the linked issue #1 with the `-i` option for your pem file

`ssh -i ~/.ssh/your.pem -N -L 3306:127.0.0.1:3306 ssh-user@remoteserver`

**Comment by aroraayush** [comment]
Yes, it is a duplicate of #1. Closing this now
